name: Mirror the monorepo in other downstream repos
description: Copy's this repo into another downstream repo
inputs:
  user-email:
    description: Email for the git commit
    required: true
  user-name:
    description: >-
      [Optional] Name for the git commit. Defaults to the destination
      username/organization name
    required: true
  repo-name:
    description: The repo that should be cloned and cherry picked from
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
    - '${{ inputs.repo-name }}'
branding:
  icon: git-commit
  color: green