compatibility_date = "2022-06-23"

name = "woodshop-api"
main = "src/index.ts"
workers_dev = true
node_compat = true
# [ secrets ] #
[ vars ]
LOG_LEVEL = "verbose"
LOG_TYPE = "json"
# WOODSHOP_API_DATABASE_URL
# WOODSHOP_API_MIGRATE_DATABASE_URL
# WOODSHOP_API_SHADOW_DATABASE_URL
# WOODSHOP_AUTH0_API_ISSUER
# WOODSHOP_AUTH0_AUDIENCE
# CLOUDFLARE_ACCOUNT_ID
# CLOUDFLARE_IMAGE_API_TOKEN

[env.production]
workers_dev = false

[ env.production.vars ]
LOG_LEVEL = "debug"
LOG_TYPE = "json"

# [ env.production.secrets ] #
# WOODSHOP_API_DATABASE_URL
# WOODSHOP_AUTH0_AUDIENCE
# WOODSHOP_AUTH0_API_ISSUER
# CLOUDFLARE_ACCOUNT_ID
# CLOUDFLARE_IMAGE_API_TOKEN
