nodeLinker: node-modules

packageExtensions:
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      medusa-interfaces: "*"
      redis-commands: "*"
      typeorm: "*"
  "@remix-run/cloudflare@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/cloudflare-pages@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/dev@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      webpack: "*"
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    dependencies:
      webpack: "*"
      "@babel/core": "*"
  "@storybook/telemetry@*":
    dependencies:
      webpack: "*"
      react: "*"
      react-dom: "*"
  medusa-fulfillment-manual@*:
    dependencies:
      "@babel/core": "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  wrangler@*:
    dependencies:
      cron-schedule: "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  remix-auth@*:
    dependencies:
      react: "*"
  remix-auth-auth0@*:
    dependencies:
      "@remix-run/server-runtime": "*"
      react: "*"
      react-dom: "*"
  remix-auth-oauth2@*:
    dependencies:
      "@remix-run/react": "*"
      react: "^18.2.0"
  "@linaria/webpack-loader@*":
    dependencies:
      webpack: "*"


  

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
