nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      redis-commands: "*"
      medusa-interfaces: "*"
      typeorm: "*"
  "@parcel/transformer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  "@remix-run/cloudflare-workers@*":
    dependencies:
      react: "*"
      react-dom: "*"
  gatsby-plugin-typescript@*:
    dependencies:
      gatsby: "*"
      react: "*"
      react-dom: "*"
  gatsby@*:
    dependencies:
      babel-eslint: "*"
  medusa-fulfillment-manual@*:
    dependencies:
      "@babel/core": "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-multi-select-component@*:
    dependencies:
      csstype: ^2.6.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
