nodeLinker: node-modules

packageExtensions:
  "@mdx-js/loader@*":
    dependencies:
      react: "*"
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      medusa-interfaces: "*"
      redis-commands: "*"
      typeorm: "*"
  "@remix-run/cloudflare@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/cloudflare-pages@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/dev@*":
    dependencies:
      react: "*"
      react-dom: "*"
      "@babel/preset-env": "*"
  "@storybook/preset-create-react-app@*":
    dependencies:
      react-refresh: "*"
      typescript: "*"
      webpack: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
      react: "*"
  medusa-fulfillment-manual@*:
    dependencies:
      "@babel/core": "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"
  wrangler@*:
    dependencies:
      cron-schedule: "*"
  "@linaria/webpack-loader@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
  remix-auth@*:
    dependencies:
      react: "*"
  remix-utils@*:
    dependencies:
      typescript: "*"
  remix-auth-oauth2@*:
    dependencies:
      "@remix-run/react": "*"
      "react": "*"
      "react-dom": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
