nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      medusa-interfaces: "*"
      redis-commands: "*"
      typeorm: "*"
  "@remix-run/cloudflare-pages@*":
    dependencies:
      react: "*"
      react-dom: "*"
  gatsby-plugin-typescript@*:
    dependencies:
      gatsby: "*"
      react: "*"
      react-dom: "*"
  gatsby@*:
    dependencies:
      babel-eslint: "*"
  medusa-fulfillment-manual@*:
    dependencies:
      "@babel/core": "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-multi-select-component@*:
    dependencies:
      csstype: ^2.6.2
  wrangler@*:
    dependencies:
      cron-schedule: "*"
  jest-config@*: 
    dependencies:
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
