nodeLinker: node-modules

packageExtensions:
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      medusa-interfaces: "*"
      redis-commands: "*"
      typeorm: "*"
  "@remix-run/cloudflare@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/cloudflare-pages@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/dev@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/addon-postcss@*":
    dependencies:
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      webpack: "*"
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    dependencies:
      webpack: "*"
      "@babel/core": "*"
  "@storybook/telemetry@*":
    dependencies:
      webpack: "*"
      react: "*"
      react-dom: "*"
  "@storybook/preset-create-react-app@*":
    dependencies:
      react-refresh: "*"
      typescript: "*"
      webpack: "*"
  "@types/react-datepicker@*":
    dependencies:
      react: "*"
      react-dom: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/core": "*"
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
      react: "*"
  medusa-fulfillment-manual@*:
    dependencies:
      "@babel/core": "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"
  wrangler@*:
    dependencies:
      cron-schedule: "*"
  remix-auth@*:
    dependencies:
      react: "*"
  remix-auth-auth0@*:
    dependencies:
      "@remix-run/server-runtime": "*"
      react: "*"
      react-dom: "*"
  remix-auth-oauth2@*:
    dependencies:
      "@remix-run/react": "*"
      react: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@linaria/webpack-loader@*":
    dependencies:
      webpack: "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  gatsby-plugin-postcss@*:
    dependencies:
      webpack: "*"
  gatsby-plugin-utils@*:
    dependencies:
      graphql: "*"
  medusa-admin@*:
    dependencies:
      prop-types: "*"
      require-from-string: "*"
  "gatsby@*":
    dependencies:
      babel-eslint: "*"
  react-hot-toast@*:
    dependencies:
      csstype: "*"
  

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
