version: "3.8"
services:
  store_api:
    image: store_api
    container_name: store_api
    build:
      context: ./
      dockerfile: ./packages/medusa/Dockerfile
    depends_on:
      - store_db
      - redis
    ports:
      - "9000:9000"

    env_file:
      - ./.env

  store_db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_db

  content_db:
    image: postgres:14
    container_name: content_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content_db
      POSTGRES_HOST_AUTH_METHOD: trust
    
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    env_file:
      - ./.env

  admin:
    image: admin
    container_name: admin
    build:
      context: ./
      dockerfile: ./packages/medusa-admin/Dockerfile
    env_file:
      - ./.env
    ports:
      - "7001:80"
