version: "3"
services:
  store_api:
    image: store_api
    container_name: store_api
    build:
      context: ./
      dockerfile: ./packages/medusa/Dockerfile
    depends_on:
      - redis
    ports:
      - "9000:9000"
    volumes:
      - /app
    env_file:
      - ./.env

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    env_file:
      - ./.env

  admin:
    image: admin
    container_name: admin
    build:
      context: ./
      dockerfile: ./packages/medusa-admin/Dockerfile
    env_file:
      - ./.env
    ports:
      - "7001:80"
