version: "3"
services:
  medusa:
    image: medusa
    build:
      context: ./
      dockerfile: ./packages/medusa/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    volumes:
      - /app
    env_file:
      - ./.env

  postgres:
    image: postgres:14
    ports:
      - "35432:5432"
    env_file:
      - ./.env

  redis:
    image: redis
    expose:
      - 6379
    env_file:
      - ./.env

  admin:
    image: admin
    build:
      context: ./
      dockerfile: ./packages/medusa-admin/Dockerfile
    env_file:
      - ./.env
    ports:
      - "7000:80"
