nodeLinker: node_modules

packageExtensions:
  "@mdx-js/loader@*":
    dependencies:
      react: "*"
  "@medusajs/medusa-cli@*":
    dependencies:
      pg: "*"
      semver: "*"
  "@medusajs/medusa@*":
    dependencies:
      medusa-interfaces: "*"
      redis-commands: "*"
      typeorm: "*"
  "@remix-run/cloudflare-pages@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/dev@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/preset-create-react-app@*":
    dependencies:
      react-refresh: "*"
      typescript: "*"
      webpack: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
      react: "*"
  medusa-telemetry@*:
    dependencies:
      "@babel/runtime": "*"
  medusa-test-utils@*:
    dependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"
  wrangler@*:
    dependencies:
      cron-schedule: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
