-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "banner_img_alt" TEXT,
ADD COLUMN     "ld_author_name" TEXT,
ADD COLUMN     "ld_date_modified" TEXT,
ADD COLUMN     "ld_date_published" TEXT,
ADD COLUMN     "ld_headline" TEXT,
ADD COLUMN     "ld_image_url" TEXT,
ADD COLUMN     "ld_logo_url" TEXT,
ADD COLUMN     "ld_publisher" TEXT,
ADD COLUMN     "ld_url" TEXT,
ADD COLUMN     "og_article_author" TEXT,
ADD COLUMN     "og_article_section" TEXT,
ADD COLUMN     "og_article_tag" TEXT[],
ADD COLUMN     "og_description" TEXT,
ADD COLUMN     "og_image" TEXT,
ADD COLUMN     "og_img_url" TEXT,
ADD COLUMN     "og_title" TEXT,
ADD COLUMN     "og_type" TEXT,
ADD COLUMN     "twitter_description" TEXT,
ADD COLUMN     "twitter_image_alt" TEXT,
ADD COLUMN     "twitter_image_url" TEXT,
ADD COLUMN     "twitter_site" TEXT,
ADD COLUMN     "twitter_title" TEXT,
ALTER COLUMN "prompt" DROP NOT NULL,
ALTER COLUMN "thumbnail_img_url" DROP NOT NULL;
