name: Deploy - Production

on:
  push:
    branches:
      - main
      - feat/database
  workflow_dispatch:

jobs:
  migrate_woodshop_api:
    runs-on: ubuntu-latest
    name: Woodshop API - Migrate DB
    environment: migrate
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_WOODSHOP_API_DATABASE_URL: ${{ secrets.WOODSHOP_API_DATABASE_URL }}
          directory: ./packages/woodshop-api/
      - name: Migrate DB
        run: yarn api:migrate

  deploy_woodshop_api:
    runs-on: ubuntu-latest
    name: Woodshop API - Build & deploy
    needs: migrate_woodshop_api
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_WOODSHOP_API_DATABASE_URL: ${{ secrets.WOODSHOP_API_DATABASE_URL }}
          directory: ./packages/woodshop-api/
      - name: Build
        run: yarn api:build
      - name: Deploy
        run: CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} yarn workspace @woodshop/api  wrangler publish --env production


  deploy_woodshop_storefront:
    name: Storefront - Push to repository
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2
      - name: Copy and clone to repo
        uses: ./.github/actions/push-storefront-to-repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

  deploy_storybook:
    runs-on: ubuntu-latest
    name: Storybook - Build & deploy
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn components-build
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./packages/components/