name: Deploy - Production

on:
  push:
    branches:
      - main
      - feat/database
  workflow_dispatch:

jobs:
  # create_woodshop_api_env:
  #   name: Woodshop API - Create .env
  #   runs-on: ubuntu-latest
  #   environment: migrate 
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/create-woodshop-api-dotenv
          
  migrate_woodshop_api:
    runs-on: ubuntu-latest
    name: Woodshop API - Migrate DB
    environment: migrate
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Migrate DB
        run: yarn api:migrate
        
  deploy_woodshop_api:
    runs-on: ubuntu-latest
    name: Woodshop API - Build & deploy
    needs: migrate_woodshop_api
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn api:build
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./packages/woodshop-api/

  deploy_woodshop_storefront:
    name: Woodshop Storefront - Push to repository
    runs-on: ubuntu-latest
    environment: production
    needs: deploy_woodshop_api
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2
      - name: Copy and clone to repo
        uses: ./.github/actions/push-storefront-to-repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

  deploy_storybook:
    runs-on: ubuntu-latest
    name: Build and Deploy - Storybook Docs
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn components-build
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./packages/components/