name: Migrate & Deploy

on:
  push:
    branches:
      - main
      - ci/update-ghactions
  workflow_dispatch:

jobs:
  migrate_woodshop_api:
    runs-on: ubuntu-latest
    name: Migrate - @woodshop/api
    environment: migrate
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Migrate Woodshop Database
        run: yarn migrate:woodshop-api

  deploy_woodshop_api:
    runs-on: ubuntu-latest
    name: Build and deploy - @woodshop/api
    needs: migrate_woodshop_api
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-api
      - name: Deploy to Cloudflare Workers
        run: 
          CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          yarn workspace @woodshop/api wrangler publish --env production

  deploy_woodshop_dashboard:
    name: Build and deploy | @woodshop/dashboard
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-dashboard
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-dashboard
          directory: packages/woodshop-dashboard/public

  deploy_components:
    name: Build and deploy | @woodshop/components
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:components
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-components
          directory: packages/components/storybook-static

  deploy_medusa_storefront:
    name: Build and deploy | medusa-storefront
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:medusa-storefront
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: medusa-storefront
          directory: packages/medusa-storefront/public

  deploy_medusa_admin:
    name: Build and deploy | medusa-admin
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:medusa-admin
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: medusa-admin
          directory: packages/medusa-admin/public
