name: Migrate & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate_woodshop_api:
    runs-on: ubuntu-latest
    name: Migrate - @woodshop/api
    environment: migrate
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Migrate Woodshop Database
        run: yarn api:migrate

  deploy_woodshop_api:
    runs-on: ubuntu-latest
    name: Build and deploy - @woodshop/api
    needs: migrate_woodshop_api
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-api
      - name: Deploy to Cloudflare Workers
        run: 
          CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          yarn workspace @woodshop/api wrangler publish --env production

  deploy_woodshop_storefront:
    name: Build and deploy | @woodshop/storefront
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-storefront
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-storefront
          directory: packages/woodshop-storefront/public

  deploy_woodshop_dashboard:
    name: Build and deploy | @woodshop/dashboard
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-dashboard
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-dashboard
          directory: packages/woodshop-dashboard/public

  deploy_woodshop_components:
    name: Build and deploy | @woodshop/components
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-components
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-components
          directory: packages/components/storybook-static

  deploy_medusa_admin:
    name: Build and deploy | medusa-admin
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:medusa-admin
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: medusa-admin
          directory: packages/medusa-admin/public
