name: Migrate & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate_woodshop_api:
    runs-on: ubuntu-latest
    name: Migrate - @woodshop/api
    environment: migrate
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Migrate Woodshop Database
        run:
          WOODSHOP_API_DATABASE_URL=${{ secrets.WOODSHOP_API_DATABASE_URL }}
          yarn workspace @woodshop/api ci:migrate

  deploy_woodshop_api:
    runs-on: ubuntu-latest
    name: Build and deploy - @woodshop/api
    needs: migrate_woodshop_api
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build & Deploy to Cloudflare Workers
        run: 
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}
          yarn workspace @woodshop/api ci:deploy

  deploy_woodshop_dashboard:
    name: Build and deploy | @woodshop/dashboard
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:woodshop-dashboard
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-dashboard
          directory: packages/woodshop-dashboard

  deploy_components:
    name: Build and deploy | @woodshop/components
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:components
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: woodshop-components
          directory: packages/components/storybook-static

  deploy_medusa_storefront:
    name: Build and deploy | medusa-storefront
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:medusa-storefront
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: medusa-storefront
          directory: packages/medusa-storefront

  deploy_medusa_admin:
    name: Build and deploy | medusa-admin
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install --immutable
      - name: Build
        run:
          GATSBY_MEDUSA_BACKEND_URL=https://api.store.themontessoriwoodshop.com
          yarn build:medusa-admin
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
          projectName: medusa-admin
          directory: packages/medusa-admin/public
